# Generated by Django 2.2.12 on 2020-09-19 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_prescription_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dosing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Prescription')),
            ],
        ),
    ]
