# Generated by Django 2.2.12 on 2020-09-19 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20200919_1852'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dosing',
            options={'ordering': ['-date']},
        ),
    ]
