# Generated by Django 2.2.12 on 2020-09-20 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20200919_2257'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Note Date')),
                ('content', models.CharField(max_length=250)),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Prescription')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
