# Generated by Django 2.2.12 on 2020-09-19 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_dosing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dosing',
            name='date',
            field=models.DateField(verbose_name='Administration Date'),
        ),
    ]
