# Generated by Django 2.2.12 on 2020-09-20 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='rx_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
