# Generated by Django 2.2.12 on 2020-09-20 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_medication'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='prescription',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.Prescription'),
            preserve_default=False,
        ),
    ]
