# Generated by Django 2.2.12 on 2020-09-22 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_emergencycontact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='instructions',
        ),
        migrations.AddField(
            model_name='prescription',
            name='times_per_day',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
