# Generated by Django 2.2.12 on 2020-09-24 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_auto_20200922_2046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medication',
            name='brand_name',
        ),
    ]
